server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    config:
      uri:  http://localhost:8888/
  zipkin:
    base-url: http://localhost:9411


