server:
  port: 8769

spring:
  application:
    name: register
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
