server:
  port: 8761

spring:
  application:
    name: register
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka/
